---
version: '3.4'
services:
  app:
    image: weeehire-ng/app
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      cache_from:
        - weeehire-ng/app
    volumes:
      # Source directories
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - ./tests:/var/www/html/tests
      - ./config:/var/www/html/config
      # Database SQL file
      - ./weeehire.db:/var/www/html/weeehire.db

  web:
    image: weeehire-ng/web
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
    ports: 
      - "8081:80"
    depends_on:
      - app
