name: CI
on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '8.0', 'latest']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          # If you use the PHPUnit action, uncomment this and comment php_extensions
          # args: --ignore-platform-reqs
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"

      - name: Create Database
        run: sqlite3 weeehire.db < database.sql

#      - name: PHPUnit Tests
#        uses: php-actions/phpunit@v2
#        with:
#          bootstrap: vendor/autoload.php
#          configuration: "tests/phpunit.xml"
#          args: --coverage-text
#          php_version: "${{ matrix.php }}"
#          php_extensions: ldap mbstring json sqlite3

      - name: PHPUnit Tests
        run: vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-text
