name: CI
on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.2', 'latest']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          # If you use the PHPUnit action, uncomment this and comment php_extensions
          # args: --ignore-platform-reqs
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"

      - name: Create Database
        run: sqlite3 database/weeehire.db < database/database.sql

      - name: Run msgfmt
        run: |
          sudo apt-get install gettext
          msgfmt resources/locale/en-US/LC_MESSAGES/messages.po --output-file=resources/locale/en-US/LC_MESSAGES/messages.mo

#      - name: PHPUnit Tests
#        uses: php-actions/phpunit@v2
#        with:
#          bootstrap: vendor/autoload.php
#          configuration: "tests/phpunit.xml"
#          args: --coverage-text
#          php_version: "${{ matrix.php }}"
#          php_extensions: ldap mbstring json sqlite3

      - name: Linting
        uses: php-actions/composer@v6
        with:
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"
          command: lint

      - name: Create config
        run: cp config/config-example.php config/config.php

      - name: Run tests
        uses: php-actions/composer@v6
        with:
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"
          command: test
