name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README*'
    - 'LICENSE'

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    
    if: github.repository_owner == 'WEEE-Open'

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to our Docker registry
      uses: docker/login-action@v1
      with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

    - name: Copy default config from example
      run: cp config/config-example.php config/config.php

    - name: Prefix image names with our custom registry domain
      run: |
        sed -i 's#image: weeehire-ng/app#image: ${{secrets.DOCKER_REGISTRY}}/weeehire-ng/app#g' docker-compose.yml
        sed -i 's#image: weeehire-ng/web#image: ${{secrets.DOCKER_REGISTRY}}/weeehire-ng/web#g' docker-compose.yml

    - name: Build the Docker images
      run: docker-compose build --pull

    - name: Push the Docker Image to our custom registry
      run: docker-compose push
