name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/**'
    - 'README*'
    - 'LICENSE'

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_REGISTRY}}/weeehire-ng:latest

    - name: Push the Docker Image to our custom registry
      run: | 
        docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}
        docker push ${{secrets.DOCKER_REGISTRY}}/weeehire-ng:latest
