name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'README*'
    - 'LICENSE'

jobs:

  build-and-push:

    runs-on: ubuntu-latest
    
    if: github.repository_owner == 'WEEE-Open'

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to our Docker registry
      uses: docker/login-action@v1
      with:
          registry: ${{secrets.DOCKER_REGISTRY}}
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_REGISTRY}}/weeehire-ng:latest

    - name: Push the Docker Image to our custom registry
      run: docker push ${{secrets.DOCKER_REGISTRY}}/weeehire-ng:latest
